#/**
# * = PLEX-META-MANAGER
# * = Master Config [.yml] v0.1
# * ********************************** *
# * keir.info - HTPC V0.1
# * ======================================================== */
# /**
# * = Define Plex Libraries
# * -------------------------------------------------------- */
libraries:                                                  # */Library mappings must have a colon (:) placed after them
  Films:
    operations:
        tmdb_collections: true
# /**
# * = Define External Services
# * -------------------------------------------------------- */
# *
#/* = Define Required Services */    
plex:
  url: http://176.9.105.216:32400
  token: iicA7vTmRs_NHodzF7VG
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: true
tmdb:                                                       # */ REQUIRED for the script to run
  apikey: 1a4081670a84cbf51d26614d480f0c35
  language: en
omdb:
  apikey: ba9a8ca5
# /**
# * = Define Global Settings
# * -------------------------------------------------------- */
# *
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  assets_for_all: true
  asset_depth: 0
  create_asset_folders: true
  download_url_assets: true
  sync_mode: sync
  collection_minimum: 1
  delete_below_minimum: true
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_missing: true
  tvdb_language: eng
  item_refresh_delay: 0
